default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV["RAILS_MAX_THREADS"] || 5 %>

development:
  <<: *default
  database: cats_development

test:
  <<: *default
  database: cats_test
